# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrequest.proto\"\xd8\x03\n\rSearchService\x1a*\n\nSearchSort\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\x05\x1a&\n\x06Second\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1a\x95\x02\n\rCommonRequest\x12\x12\n\nsearchType\x18\x01 \x01(\t\x12\x12\n\nsearchWord\x18\x02 \x01(\t\x12-\n\nsearchSort\x18\x03 \x01(\x0b\x32\x19.SearchService.SearchSort\x12*\n\x0bsecondsList\x18\x04 \x03(\x0b\x32\x15.SearchService.Second\x12\x13\n\x0b\x63urrentPage\x18\x05 \x01(\x05\x12\x10\n\x08pageSize\x18\x06 \x01(\x05\x12\x13\n\x0bsearchScope\x18\x07 \x01(\x05\x12\x18\n\x10searchFilterList\x18\x08 \x03(\x05\x12\x16\n\x0elanguageExpand\x18\t \x01(\x08\x12\x13\n\x0btopicExpand\x18\n \x01(\x08\x1a[\n\rSearchRequest\x12\x33\n\rcommonRequest\x18\x01 \x01(\x0b\x32\x1c.SearchService.CommonRequest\x12\x15\n\rinterfaceType\x18\x02 \x01(\x05\x62\x06proto3'
)




_SEARCHSERVICE_SEARCHSORT = _descriptor.Descriptor(
  name='SearchSort',
  full_name='SearchService.SearchSort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='SearchService.SearchSort.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='SearchService.SearchSort.order', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=77,
)

_SEARCHSERVICE_SECOND = _descriptor.Descriptor(
  name='Second',
  full_name='SearchService.Second',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='SearchService.Second.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SearchService.Second.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=117,
)

_SEARCHSERVICE_COMMONREQUEST = _descriptor.Descriptor(
  name='CommonRequest',
  full_name='SearchService.CommonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='searchType', full_name='SearchService.CommonRequest.searchType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchWord', full_name='SearchService.CommonRequest.searchWord', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchSort', full_name='SearchService.CommonRequest.searchSort', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secondsList', full_name='SearchService.CommonRequest.secondsList', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='SearchService.CommonRequest.currentPage', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='SearchService.CommonRequest.pageSize', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchScope', full_name='SearchService.CommonRequest.searchScope', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchFilterList', full_name='SearchService.CommonRequest.searchFilterList', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='languageExpand', full_name='SearchService.CommonRequest.languageExpand', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicExpand', full_name='SearchService.CommonRequest.topicExpand', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=397,
)

_SEARCHSERVICE_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='SearchService.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commonRequest', full_name='SearchService.SearchRequest.commonRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interfaceType', full_name='SearchService.SearchRequest.interfaceType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=490,
)

_SEARCHSERVICE = _descriptor.Descriptor(
  name='SearchService',
  full_name='SearchService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_SEARCHSERVICE_SEARCHSORT, _SEARCHSERVICE_SECOND, _SEARCHSERVICE_COMMONREQUEST, _SEARCHSERVICE_SEARCHREQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=490,
)

_SEARCHSERVICE_SEARCHSORT.containing_type = _SEARCHSERVICE
_SEARCHSERVICE_SECOND.containing_type = _SEARCHSERVICE
_SEARCHSERVICE_COMMONREQUEST.fields_by_name['searchSort'].message_type = _SEARCHSERVICE_SEARCHSORT
_SEARCHSERVICE_COMMONREQUEST.fields_by_name['secondsList'].message_type = _SEARCHSERVICE_SECOND
_SEARCHSERVICE_COMMONREQUEST.containing_type = _SEARCHSERVICE
_SEARCHSERVICE_SEARCHREQUEST.fields_by_name['commonRequest'].message_type = _SEARCHSERVICE_COMMONREQUEST
_SEARCHSERVICE_SEARCHREQUEST.containing_type = _SEARCHSERVICE
DESCRIPTOR.message_types_by_name['SearchService'] = _SEARCHSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchService = _reflection.GeneratedProtocolMessageType('SearchService', (_message.Message,), {

  'SearchSort' : _reflection.GeneratedProtocolMessageType('SearchSort', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE_SEARCHSORT,
    '__module__' : 'request_pb2'
    # @@protoc_insertion_point(class_scope:SearchService.SearchSort)
    })
  ,

  'Second' : _reflection.GeneratedProtocolMessageType('Second', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE_SECOND,
    '__module__' : 'request_pb2'
    # @@protoc_insertion_point(class_scope:SearchService.Second)
    })
  ,

  'CommonRequest' : _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE_COMMONREQUEST,
    '__module__' : 'request_pb2'
    # @@protoc_insertion_point(class_scope:SearchService.CommonRequest)
    })
  ,

  'SearchRequest' : _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE_SEARCHREQUEST,
    '__module__' : 'request_pb2'
    # @@protoc_insertion_point(class_scope:SearchService.SearchRequest)
    })
  ,
  'DESCRIPTOR' : _SEARCHSERVICE,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:SearchService)
  })
_sym_db.RegisterMessage(SearchService)
_sym_db.RegisterMessage(SearchService.SearchSort)
_sym_db.RegisterMessage(SearchService.Second)
_sym_db.RegisterMessage(SearchService.CommonRequest)
_sym_db.RegisterMessage(SearchService.SearchRequest)


# @@protoc_insertion_point(module_scope)
